---
- hosts: database
- name: install mysql
  hosts: webservers
  become: true
  become_user: root
  gather_facts: true
  tasks:
  - name: "Install php-mysql"
    apt: name=php5-mysql state=present
  - name: "Install mysqlserver"
    apt: name=mysql-server state=present
 
